# Jekyll Configuration File
# This file is used to configure the Jekyll site.
# For more information on configuration options, see:
# https://jekyllrb.com/docs/configuration/

# Site settings
title: LukeZ Wiki
description: A knowledge base for LukeZ projects, built with Jekyll
url: "https://the-lukez.github.io"
baseurl: "/"

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima

# Collections (optional, for organizing content)
collections:
  pages:
    output: true
    permalink: /:name/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Exclude files from build
exclude:
  - README.md
  - .github/

header_pages:
  - index.md
  - about.md